# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:  /blog/:title
# relative_permalinks: true

# Setup
title:            Santhosh Vaiyapuri
tagline:          'Personal Website'
description:      'This is the Personal Webpage of Santhosh Vaiyapuri. It also links to his resume and blog.'
url:              http://santhosh.info
baseurl:          /

author:
  name:           'Santhosh Vaiyapuri'
  twitter:        'santhoshvai'
  url:            https://twitter.com/santhoshvai

# paginate:         5

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

exclude: [node_modules, gulpfile.js, package.json, Gemfile]
# Google
# http://static.googleusercontent.com/media/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf
